package domain.formulario;

public enum TipoCampo {
    CAMPO_TEXTO,
    CAMPO_NUMERICO,
    CAMPO_FECHA,
    CAMPO_MULTIPLE,
    CAMPO_FECHA_NACIMIENTO,
    CAMPO_FECHA_DONACION,
    CAMPO_NOMBRE,
    CAMPO_EMAIL,
    CAMPO_TELEFONO,
}
