package domain.formulario;

// Enum para los tipos de entrada
public enum TipoEntrada {
    ENTRADA_NUMERICA,
    ENTRADA_TEXTO,
    ENTRADA_TIPO_SELECCION,
    ENTRADA_TIPO_FECHA,
    ENTRADA_RESPUESTA_MULTIPLE,
    ENTRADA_RESPUESTA_BOOLEANA,
    ENTRADA_EMAIL,
    ENTRADA_WHATSAPP,
    ENTRADA_TELEFONO
}
